pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            url = "https://maven.kikugie.dev/releases"
            name = "KikuGie Releases"
        }
        maven {
            url = "https://maven.kikugie.dev/snapshots"
            name = "KikuGie Snapshots"
        }
        gradlePluginPortal()
    }
}

plugins {
    id("dev.kikugie.stonecutter").version "0.9.8"
    id("dev.kikugie.loom-back-compat").version "0.4.2"
}

stonecutter {
    create(rootProject) {
        versions("1.21.11")
        version("26.2.x", "26.2")
        vcsVersion = "26.2.x"
    }
}

rootProject.name = "HousingCreativeTab"