mod.id = "housingcreativetab-lite"
mod.name = "HousingCreativeTab-Lite"
mod.group = "xyz.busterbrown1218.xyz"
mod.version = "1.0.1"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"

["1.21.11"]
mod.mc_compat = "1.21.11"
mod.mc_releases = ["1.21.11"]

deps.fabric_api = "0.141.6+1.21.11"
deps.mod_menu = "17.0.1-beta.1"

["26.2.x"]
mod.mc_compat = "~26.2"
mod.mc_releases = ["26.2"]

deps.fabric_api = "0.156.0+26.2"
deps.mod_menu = "20.0.1"
